import{a as M,S as C,i as u}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const R="https://pixabay.com/api/",$="52252669-cc5c6090dc05e341eb544e959";async function L(n,t=1){try{return(await M.get(R,{params:{key:$,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch(i){throw i}}const b=document.querySelector(".gallery"),c=document.getElementById("load-more");let a=document.getElementById("loader");a||(a=document.createElement("div"),a.id="loader",a.classList.add("loader","visually-hidden"),c&&c.insertAdjacentElement("beforebegin",a));const v=new C(".gallery a",{captionsData:"alt",captionDelay:250});function w(n){if(!(n!=null&&n.length))return;const t=n.map(({webformatURL:i,largeImageURL:o,tags:e,likes:r,views:d,comments:A,downloads:I})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o}">
          <img class="gallery-image" src="${i}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${r}</p>
          <p class="info-item"><b>Views:</b> ${d}</p>
          <p class="info-item"><b>Comments:</b> ${A}</p>
          <p class="info-item"><b>Downloads:</b> ${I}</p>
        </div>
      </li>`).join("");b.insertAdjacentHTML("beforeend",t),v.refresh()}function O(){b.innerHTML="",v.refresh()}function E(){a&&a.classList.remove("visually-hidden")}function S(){a&&a.classList.add("visually-hidden")}function B(){c&&c.classList.remove("visually-hidden")}function f(){c&&c.classList.add("visually-hidden")}const q=document.querySelector(".form"),l=q.querySelector("input"),p=document.getElementById("load-more");let s=1,y="",m=0;function g(){l.classList.add("input-error"),l.value="",l.focus()}function P(){l.classList.remove("input-error")}function h(){u.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}q.addEventListener("submit",x);p.addEventListener("click",H);async function x(n){var i;n.preventDefault();const t=l.value.trim();if(P(),!t){g(),u.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"});return}y=t.toLowerCase(),s=1,m=0,l.value="",O(),f(),E();try{const o=await L(y,s);if(!((i=o.hits)!=null&&i.length)){g(),u.error({title:"No results",message:"Sorry, no images found.",position:"topRight"});return}m=o.totalHits,w(o.hits),document.querySelectorAll(".gallery .gallery-item").length>=m?(f(),h()):B()}catch(o){console.error(o),f(),g(),u.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{S()}}async function H(){var n;if(y){s+=1,E(),p.disabled=!0;try{const t=await L(y,s);if(!((n=t.hits)!=null&&n.length)){f(),h();return}const i=document.querySelectorAll(".gallery .gallery-item").length;w(t.hits);const o=document.querySelectorAll(".gallery .gallery-item")[i];if(o){const r=o.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}document.querySelectorAll(".gallery .gallery-item").length>=m?(f(),h()):B()}catch(t){console.error(t),s=Math.max(1,s-1),u.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{S(),p.disabled=!1}}}
//# sourceMappingURL=index.js.map
