import{a as q,S as O,i as c}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const P="https://pixabay.com/api/",x="52252669-cc5c6090dc05e341eb544e959";async function L(o,t=1){try{return(await q.get(P,{params:{key:x,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch(n){throw n}}const b=document.querySelector(".gallery"),f=document.getElementById("loader"),p=document.getElementById("load-more"),v=new O(".gallery a",{captionsData:"alt",captionDelay:250});function w(o){if(!(o!=null&&o.length))return;const t=o.map(({webformatURL:n,largeImageURL:i,tags:e,likes:r,views:l,comments:R,downloads:$})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${n}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${r}</p>
          <p class="info-item"><b>Views:</b> ${l}</p>
          <p class="info-item"><b>Comments:</b> ${R}</p>
          <p class="info-item"><b>Downloads:</b> ${$}</p>
        </div>
      </li>`).join("");b.insertAdjacentHTML("beforeend",t),v.refresh()}function H(){b.innerHTML="",v.refresh()}function E(){f&&f.classList.remove("visually-hidden")}function S(){f&&f.classList.add("visually-hidden")}function B(){p&&p.classList.remove("visually-hidden")}function u(){p&&p.classList.add("visually-hidden")}const I=document.querySelector(".form"),a=I.querySelector("input"),m=document.getElementById("load-more"),M=15;let s=1,h="",d=0;function y(){a.classList.add("input-error"),a.value="",a.focus()}function T(){a.classList.remove("input-error")}function g(){c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}I.addEventListener("submit",A);m&&m.addEventListener("click",C);async function A(o){var n;o.preventDefault();const t=a.value.trim();if(T(),!t){y(),c.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"});return}h=t.toLowerCase(),s=1,d=0,a.value="",H(),u(),E();try{const i=await L(h,s);if(!((n=i.hits)!=null&&n.length)){y(),c.error({title:"No results",message:"Sorry, no images found.",position:"topRight"});return}d=i.totalHits,w(i.hits),d>M?B():u()}catch(i){console.error(i),u(),y(),c.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{S()}}async function C(){var o;if(h){s+=1,E(),m.disabled=!0;try{const t=await L(h,s);if(!((o=t.hits)!=null&&o.length)){u(),g();return}w(t.hits);const n=document.querySelector(".gallery .gallery-item");if(n){const i=n.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}s*M>=d?(u(),g()):B()}catch(t){console.error(t),s=Math.max(1,s-1),c.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{S(),m.disabled=!1}}}
//# sourceMappingURL=index.js.map
