import{a as $,S as R,i as u}from"./assets/vendor-qhGxV49-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const A="https://pixabay.com/api/",O="52252669-cc5c6090dc05e341eb544e959";async function b(n,t=1){try{return(await $.get(A,{params:{key:O,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch(r){throw r}}const w=document.querySelector(".gallery"),a=document.getElementById("loader"),l=document.getElementById("load-more"),x=new R(".gallery a",{captionsData:"alt",captionDelay:250});function E(n){if(!(n!=null&&n.length))return;const t=n.map(({webformatURL:r,largeImageURL:i,tags:e,likes:o,views:c,comments:M,downloads:P})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${r}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${o}</p>
          <p class="info-item"><b>Views:</b> ${c}</p>
          <p class="info-item"><b>Comments:</b> ${M}</p>
          <p class="info-item"><b>Downloads:</b> ${P}</p>
        </div>
      </li>
    `).join("");w.insertAdjacentHTML("beforeend",t),x.refresh()}function j(){w.innerHTML=""}function S(){!a||!l||(l.insertAdjacentElement("beforebegin",a),a.classList.remove("visually-hidden"),a.classList.add("is-loading"))}function B(){a&&(a.classList.add("visually-hidden"),a.classList.remove("is-loading"))}function I(){l&&l.classList.remove("visually-hidden")}function h(){l&&l.classList.add("visually-hidden")}const q=document.querySelector(".form"),f=q.querySelector("input"),C=document.querySelector(".gallery"),L=document.getElementById("load-more"),m=15;let s=1,y="",g=0;L&&L.classList.add("visually-hidden");let d=document.getElementById("loader");d||(d=document.createElement("div"),d.id="loader",d.classList.add("loader","visually-hidden"));C.insertAdjacentElement("afterend",d);function p(){f.classList.add("input-error"),f.value="",f.focus()}function D(){f.classList.remove("input-error")}function v(){u.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}q.addEventListener("submit",H);L.addEventListener("click",N);async function H(n){var r;n.preventDefault();const t=f.value.trim();if(D(),!t){p(),u.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"});return}y=t.toLowerCase(),s=1,g=0,j(),h(),S();try{const i=await b(y,s,m);if(!((r=i.hits)!=null&&r.length)){p(),u.error({title:"No results",message:"Sorry, there are no images matching your search query.",position:"topRight"});return}g=i.totalHits||0,E(i.hits),s*m<g?I():h()}catch(i){console.error(i),p(),u.error({title:"Error",message:"Something went wrong while fetching images. Please try again later.",position:"topRight"})}finally{B()}}async function N(){var n;if(y){s+=1,S();try{const t=await b(y,s,m);if(!((n=t.hits)!=null&&n.length)){h(),v();return}E(t.hits);const r=document.querySelectorAll(".gallery .gallery-item");if(r.length>m){const{top:i}=r[r.length-t.hits.length].getBoundingClientRect();window.scrollBy({top:i-20,behavior:"smooth"})}s*m>=g?(h(),v()):I()}catch(t){console.error(t),s=Math.max(1,s-1),u.error({title:"Error",message:"Something went wrong while fetching more images. Please try again later.",position:"topRight"})}finally{B()}}}
//# sourceMappingURL=index.js.map
